no_of_episodes: 50
auto_reset: true

task_mode:
  scenario:
    scenario_file: default.json

  parametrized:
    file: default.xml 

  staged:
    curriculum: "default.yaml"
    starting_index: 0

  dynamic_map: {}

  random:
    static:
      min: 0
      max: 0
      models: ["shelf"]
    interactive:
      min: 0
      max: 0
      models: ["shelf"]
    dynamic:
      min: 5
      max: 5
      models: ["actor1"]


pedsim:
  default_actor_config:
    VMAX: [0.3, 0.5]
    MAX_TALKING_DISTANCE: 1
    TALKING_BASE_TIME: 5
    CHATTING_PROBABILITY: 0
    TELL_STORY_PROBABILITY: 0
    GROUP_TALKING_PROBABILITY: 0
    TALKING_AND_WALKING_PROBABILITY: 0
    TELL_STORY_BASE_TIME: 5
    FORCE_FACTOR_DESIRED: [1, 5]
    FORCE_FACTOR_OBSTACLE: [1, 7]
    FORCE_FACTOR_SOCIAL: [5, 8]
    FORCE_FACTOR_ROBOT: [2, 10]
    WAYPOINT_MODE: 1