#! /usr/bin/bash

export BUILD_EXCLUDES=""

ARENA_WS_DIR="$(pwd)"

source $(cd src/arena/arena-rosnav && poetry env info -p)/bin/activate
colcon build \
    --symlink-install \
    --continue-on-error \
    --packages-skip-build-finished \
    --packages-ignore vcstool qt_gui_cpp rqt_gui_cpp qt_gui_core rqt \
    --cmake-args -DPython3_ROOT_DIR=$(cd src/arena/arena-rosnav && poetry env info -p) -DBUILD_TESTING=OFF \
    $@

cd $ARENA_WS_DIR
source install/local_setup.bash

# Add Gazebo environment variables
export GZ_CONFIG_PATH="${ARENA_WS_DIR}/install/gz-sim7/share/gz"
export GZ_SIM_PHYSICS_ENGINE_PATH="${ARENA_WS_DIR}/build/gz-physics6"
export GZ_SIM_RESOURCE_PATH="\
${ARENA_WS_DIR}/src/deps/robots/jackal:\
${ARENA_WS_DIR}/src/arena/simulation-setup/entities:\
${ARENA_WS_DIR}/src/arena/simulation-setup/worlds:\
${ARENA_WS_DIR}/src/arena/simulation-setup/gazebo_models:\
${ARENA_WS_DIR}/src/arena/simulation-setup/gazebo_models/Cafe table/materials/textures"

for package in $(ls /opt/ros/humble/share/) ; do
    setup_file="/opt/ros/humble/share/${package}/local_setup.bash"
    if [ -f "$setup_file" ] ; then
        . "$setup_file"
    fi 
done